Print jstest result summary

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -74,6 +74,12 @@ jobs:
         run:  |
           python3 js/src/tests/parse_output.py
 
+      - name: Print Test Summary
+        if:  ${{ (success() || failure()) }} # run this step even if previous step failed
+        run: |
+          cat ./jstest_dump.txt
+          cat ./jstest_output.md >> $GITHUB_STEP_SUMMARY
+
       - name: Upload Report
         uses: actions/upload-artifact@v4  # upload test results
         if:  ${{ matrix.taintspew == 'false' &&  matrix.jitspew == 'false' && (success() || failure()) }} # run this step even if previous step failed
@@ -87,8 +93,3 @@ jobs:
         with:
           name: spidermonkey
           path: obj-spider-release/dist/bin
-
-      - name: Show Summary
-        run: |
-          cat ./jstest_output.xml >> $GITHUB_STEP_SUMMARY
-      
