Upload build artifacts (#263)
* Upload build artifacts
* Update LLVM to fix build errors
* Upload Spidermonkey Binary
* Update dependency name
* Add Ubuntu browser tests
* Move around build steps
* Correct config file for SpiderMonkey
* Fixing JitSpew typo
* Enable js shell for tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: CI
+name: JavaScript
 
 # Controls when the workflow will run
 on:
@@ -37,28 +37,14 @@ jobs:
           pip install junit-xml
 
       - name: Checkout release branch
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
-          ref: firefox-release
-          path: release
+          fetch-depth: 1
 
-      # Bootstrap
-      - name: Bootstrap Build Tools
+      - name: Copy Configuration
         run: |
-          cd release
-          ./mach --no-interactive bootstrap --application-choice=js
-
-      - name: Checkout release branch
-        uses: actions/checkout@v3
-        with:
-            path: build
-    
-      # Configure
-      - name: Copy configuration
-        run: |
-          cd build
           cp taintfox_mozconfig_spidermonkey .mozconfig
-
+    
       - name: Enable JitSpew
         if: ${{ matrix.jitspew == 'true' }}
         run: echo "ac_add_options --enable-jitspew" >> .mozconfig
@@ -66,22 +52,23 @@ jobs:
       - name: Enable TaintSpew
         if: ${{ matrix.taintspew == 'true' }}
         run: echo "ac_add_options --enable-taintspew" >> .mozconfig
-
+        
+      - name: Bootstrap Build Tools
+        run: |
+          ./mach --no-interactive bootstrap --application-choice=js
+      
       # Build
       - name: Build
         run: |
-          cd build
           ./mach build
 
       # Test
       - name: Test
         run:  |
-          cd build
           obj-spider-release/dist/bin/js js/src/Y.js
 
       - name: Taint Tests
         run:  |
-          cd build
           python3 js/src/tests/parse_output.py
 
       - name: Upload Report
@@ -89,4 +76,11 @@ jobs:
         if:  ${{ matrix.taintspew == 'false' &&  matrix.jitspew == 'false' && (success() || failure()) }} # run this step even if previous step failed
         with:
           name: test-results
-          path: build/jstest_output.xml
+          path: jstest_output.xml
+
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v4  # upload test results
+        if:  ${{ matrix.taintspew == 'false' &&  matrix.jitspew == 'false' && (success() || failure()) }} # run this step even if previous step failed
+        with:
+          name: spidermonkey
+          path: obj-spider-release/dist/bin
